language: node_js
node_js:
  - "7"
branches:
  only:
    - master
install : 
  - npm install -g firebase-tools
  - cd functions && npm install

after_success:
   - firebase deploy --token $FIREBASE_TOKEN
